from faker import Faker

CREATE TABLE Users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    balance DECIMAL DEFAULT 0,
    CHECK(balance >= 0)
);


for _ in range(1000):
    fake_data["first_name"]
    fake_data["first_name"].append( fake.first_name() )
    fake_data["last_name"].append( fake.last_name() )
    fake_data["address"].append( fake.address() )
    fake_data["dob"].append( fake.date_of_birth() )
    fake_data["country"].append( fake.country() )